services:
  - docker:19.03

stages:
  - build
#  - start
#  - tests


maven-build:
  stage: build
  tags:
    - ci
  image: maven:3-jdk-11
  before_script:
    - cd BackEnd
  script: mvn clean install -Dskip.surefire.tests


