services:
  - docker:19.03

stages:
    - build
    - test

maven-build:
  stage: build
  image: maven:3-jdk-11
  before_script:
    - cd BackEnd
  script: mvn clean install -Dskip.surefire.tests

angular-build:
    stage: build
    image: trion/ng-cli
    before_script:
        - cd FrontEnd/angular
        - npm ci
    script:
        - ng build
    artifacts:
        expire_in: 1 day
        paths:
            - dist/
    tags:
        - docker

angular-test-karma:
    stage: test
    image: trion/ng-cli-karma
    allow_failure: false
    dependencies:
        - angular-build
    before_script:
        - cd FrontEnd/angular
        - ls
    script:
        - ng test
    tags:
        - docker

angular-test-e2e:
    stage: test
    image: trion/ng-cli-e2e
    allow_failure: false
    before_script:
        - cd FrontEnd/angular
    script:
        - ng e2e
    tags:
        - docker

angular-test-lint:
    stage: test
    image: trion/ng-cli
    before_script:
        - cd FrontEnd/angular
    script:
        - ng lint
    tags:
        - docker

angular-lint-sonar:
    stage: test
    image: trion/ng-cli
    before_script:
        - cd FrontEnd/angular
    script:
        - npm install -g sonarqube-scanner
        - >
            sonar-scanner
            -Dsonar.projectKey=demo
            -Dsonar.organization=everflux-github
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=covfefe
            -Dsonar.typescript.lcov.reportPaths=coverage/lcov/lcov.info
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.sources=src/app
            -Dsonar.exclusions=**/node_modules/**,**/*.spec.ts
            -Dsonar.tests=src/app
            -Dsonar.test.inclusions=**/*.spec.ts







