version: '3'
services:
  eureka:
    build: eureka-server
    ports:
      - 8761:8761

  gateway:
    build: gateway
    links:
      - eureka
    ports:
      - 8080:8080
    depends_on:
      - eureka
