stages:
    - build
    - test

build:
    stage: build
    image: trion/ng-cli
    before_script:
        - npm ci
    script:
        - ng build
    artifacts:
        expire_in: 1 day
        paths:
            - dist/
    tags:
        - docker

test:karma:
    stage: test
    image: trion/ng-cli-karma
    allow_failure: false
    script:
        - ng test
    tags:
        - docker

test:e2e:
    stage: test
    image: trion/ng-cli-e2e
    allow_failure: false
    script:
        - ng e2e
    tags:
        - docker

test:lint:
    stage: test
    image: trion/ng-cli
    script:
        - ng lint
    tags:
        - docker

lint:sonar:
    stage: test
    image: trion/ng-cli
    script:
        - npm install -g sonarqube-scanner
        - >
            sonar-scanner
            -Dsonar.projectKey=demo
            -Dsonar.organization=everflux-github
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=covfefe
            -Dsonar.typescript.lcov.reportPaths=coverage/lcov/lcov.info
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.sources=src/app
            -Dsonar.exclusions=**/node_modules/**,**/*.spec.ts
            -Dsonar.tests=src/app
            -Dsonar.test.inclusions=**/*.spec.ts




