spring:
  application:
    name: authentication
  cloud:
    refresh:
      refreshable: none
  datasource:
    username: root
    password: 123456
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update #create for drop previous data

server:
  port: 8766


