
server:
  port: 8762

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 50
    statusPageUrlPath: /info
    healthCheckUrlPath: /health

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
